sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
install:
  - npm install
script:
  - npm test
after_script:
  - npm run coverage && cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js